[package]
name = "proof-of-innocence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dusk-jubjub = "0.12.1"
dusk-plonk = "0.13.1"
rand_core = "0.6.4"
