[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.12", default-features = false }
serde = "1.0"
getrandom = { version = "0.2", features = ["js"] }
serde_json = "1.0.94"
circuit = { path = "../../circuit" }
